#!/usr/bin/env node
/**
 * Switches the app to LOCAL mode:
 *  - SQLite database (no PostgreSQL needed)
 *  - Auth disabled (no login required)
 *
 * To restore production mode, run:  npm run use:prod
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const root = path.resolve(__dirname, "..");
const SQLITE_URL = "file:./dev.db";

console.log("🔄  Switching to LOCAL mode (SQLite + no auth)...\n");

// 1. Copy SQLite schema → active schema.prisma
fs.copyFileSync(
  path.join(root, "prisma/schema.sqlite.prisma"),
  path.join(root, "prisma/schema.prisma")
);
console.log("✅  Prisma schema switched to SQLite");

// 2. Write .env.local (Next.js picks this up automatically, overrides .env)
const envLocal = [
  `# AUTO-GENERATED by scripts/use-local.js — do not edit manually`,
  `# Delete this file (or run npm run use:prod) to restore production mode`,
  `DATABASE_URL="${SQLITE_URL}"`,
  `DISABLE_AUTH="true"`,
  `AUTH_SECRET="local-dev-secret-not-for-production"`,
  `NEXTAUTH_URL="http://localhost:3000"`,
].join("\n") + "\n";

fs.writeFileSync(path.join(root, ".env.local"), envLocal);
console.log("✅  .env.local written (SQLite URL + DISABLE_AUTH=true)");

// 3. Push schema to SQLite (no interactive prompts, resets existing local db)
console.log("\n🔄  Pushing schema to SQLite (prisma db push)...");
execSync("npx prisma db push --force-reset --accept-data-loss", {
  stdio: "inherit",
  cwd: root,
  env: { ...process.env, DATABASE_URL: SQLITE_URL },
});

// 4. Regenerate Prisma client for SQLite
console.log("\n🔄  Regenerating Prisma client for SQLite...");
execSync("npx prisma generate", { stdio: "inherit", cwd: root });

// 5. Seed the admin account
console.log("\n🔄  Seeding admin account...");
execSync("npm run db:seed", {
  stdio: "inherit",
  cwd: root,
  env: { ...process.env, DATABASE_URL: SQLITE_URL, DISABLE_AUTH: "true" },
});

console.log(`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅  LOCAL MODE ACTIVE

  Database : SQLite (prisma/dev.db)
  Auth     : DISABLED — no login needed

  Start the app:  npm run dev
  Open browser:   http://localhost:3000

  To restore production mode:
    npm run use:prod
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`);
